[package]
name = "flysky-i6x-rs"
version = "0.11.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"
stm32f0xx-hal = { version = "0.18.0", features = ["stm32f072", "rt"] }
embedded-graphics = "0.8.1"

[features]
default = ["stm32"]
stm32 = []
apm32 = []

[profile.dev]
opt-level = 1
debug = true

[profile.release]
opt-level = "z"     # Optimize for size
lto = "fat"         # Enable Link-Time Optimization
codegen-units = 1   # Maximize LTO optimization across crates
panic = "abort"     # Remove stack unwinding overhead
debug = true        # Keep debug symbols for probe-rs / GDB
